[target.aarch64-linux-android]
rustflags = ["-C", "link-arg=-landroid", "-C", "link-arg=-llog", "-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2"]

[target.armv7-linux-androideabi]
rustflags = ["-C", "link-arg=-landroid", "-C", "link-arg=-llog", "-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2"]

[target.i686-linux-android]
rustflags = ["-C", "link-arg=-landroid", "-C", "link-arg=-llog", "-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2"]

[target.x86_64-linux-android]
rustflags = ["-C", "link-arg=-landroid", "-C", "link-arg=-llog", "-C", "link-arg=-lEGL", "-C", "link-arg=-lGLESv2"] 